"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# GOOD: Secret key .env se
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable not set!")


# SECURITY WARNING: don't run with debug turned on in production!
# GOOD: Debug sirf development mein
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# GOOD: Allowed hosts explicitly define karo
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.authentication',
    'apps.m2m'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # GOOD: Dev mein sqlite, production mein .env se postgres URL
        'NAME': BASE_DIR / os.environ.get('DB_NAME', 'db.sqlite3'),
    }
}

# ============================================================
# SESSION — GOOD: Session-based state storage OAuth ke liye
# ============================================================
 
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_HTTPONLY = True    # GOOD: JS se inaccessible
SESSION_COOKIE_SECURE = not DEBUG  # GOOD: Production mein HTTPS only
SESSION_COOKIE_SAMESITE = 'Lax'   # GOOD: CSRF mitigation
SESSION_COOKIE_AGE = 3600         # GOOD: 1 hour — phir expire

# ============================================================
# OAUTH 2.0 SETTINGS — GOOD: Sab ek jagah, .env se
# ============================================================
 
OAUTH = {
    # Authorization Code Flow settings
    'AUTH_CODE_EXPIRY': int(os.environ.get('OAUTH_AUTH_CODE_EXPIRY', 600)),   # 10 min
    'ACCESS_TOKEN_EXPIRY': int(os.environ.get('OAUTH_ACCESS_TOKEN_EXPIRY', 3600)),  # 1 hour
    'REFRESH_TOKEN_EXPIRY': int(os.environ.get('OAUTH_REFRESH_TOKEN_EXPIRY', 2592000)),  # 30 days
 
    # GOOD: State parameter expiry — stale state reject karo
    'STATE_EXPIRY': int(os.environ.get('OAUTH_STATE_EXPIRY', 600)),  # 10 min
 
    # GOOD: Supported grant types explicitly define karo
    'SUPPORTED_GRANT_TYPES': [
        'authorization_code',
        'refresh_token',
        'client_credentials',
    ],
 
    # GOOD: Supported scopes — server pe whitelist
    'SUPPORTED_SCOPES': [
        'openid',
        'profile',
        'email',
        'read:data',
        'write:data',
        'offline_access',
    ],
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# ============================================================
# SECURITY HEADERS — GOOD: Production hardening
# ============================================================
 
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
