# Generated by Django 5.2.12 on 2026-03-26 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('client_type', models.CharField(choices=[('service', 'Backend Service')], default='service', max_length=20)),
                ('allowed_scopes', models.JSONField(default=list, help_text="e.g. ['read:orders', 'write:analytics']")),
                ('allowed_services', models.JSONField(default=list, help_text='Service names this client can call. Empty = no restriction.')),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Max token requests per minute. 0 = unlimited (not recommended).')),
                ('token_ttl_seconds', models.IntegerField(default=3600, help_text='Access token lifetime. Sensitive services: 900 (15 min).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_token_issued_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm2m_service_clients',
            },
        ),
        migrations.CreateModel(
            name='TokenRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('scopes_requested', models.JSONField(default=list)),
                ('scopes_granted', models.JSONField(default=list)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2m.serviceclient')),
            ],
            options={
                'db_table': 'm2m_token_request_logs',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=2000, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='m2m.serviceclient')),
            ],
            options={
                'db_table': 'm2m_service_tokens',
                'indexes': [models.Index(fields=['token'], name='m2m_token_idx'), models.Index(fields=['service', 'revoked'], name='m2m_service_revoked_idx')],
            },
        ),
    ]
