# Generated by Django 5.2.12 on 2026-03-26 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('redirect_uris', models.TextField(help_text='One redirect URI per line. Exact match required.')),
                ('allowed_grant_types', models.JSONField(default=list, help_text="e.g. ['authorization_code', 'refresh_token']")),
                ('allowed_scopes', models.JSONField(default=list, help_text='Scopes this client is allowed to request')),
                ('is_active', models.BooleanField(default=True)),
                ('pkce_required', models.BooleanField(default=True, help_text='Require PKCE for this client. Must be True for public clients (SPA, mobile). RFC 9700 recommends True for all clients.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oauth_clients',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('redirect_uri', models.URLField()),
                ('scopes', models.JSONField(default=list)),
                ('code_challenge', models.CharField(blank=True, max_length=255)),
                ('code_challenge_method', models.CharField(blank=True, choices=[('S256', 'SHA-256'), ('plain', 'Plain')], max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.oauthclient')),
            ],
            options={
                'db_table': 'oauth_auth_codes',
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=2000, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.oauthclient')),
            ],
            options={
                'db_table': 'oauth_access_tokens',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to='authentication.accesstoken')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.oauthclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_refresh_tokens',
            },
        ),
    ]
